export const IDENTITY_SERVICE_TOKEN: string = 'IDENTITY_SERVICE_TOKEN'; 
export const PAYMENTS_SERVICE_TOKEN: string = 'PAYMENTS_SERVICE_TOKEN'; 
export const CUSTOMERS_SERVICE_TOKEN: string = 'CUSTOMERS_SERVICE_TOKEN'; 
